start = sdf-mapping

sdf-mapping = {
 ; info will be required in most process policies, but omission is
 ; not a syntax error:
 ? info: sdfinfo
 ? namespace: named<text>
 ? defaultNamespace: text
 ? map: { * sdf-pointer => additionalqualities}
}

; we can't really be much more specific here:
additionalqualities = named<any>

; --------------------------------- import from SDF:

sdfinfo = {
 ? title: text
 ? version: text
 ? copyright: text
 ? license: text
 EXTENSION-POINT<"info-ext">
}

; Shortcut for a map that gives names to instances of X (has
; text keys and values of type X)
named<X> = { * text => X }

; only used in framework syntax:
EXTENSION-POINT<f> = ( * (text .feature f) => any )

sdf-pointer = text ; .regexp curie-regexp -- TO DO!
